// vue-remote-mf-app/src/App.vue
<script setup lang="ts">
import { ref } from 'vue'
import { inject } from 'vue';
import { IStore } from './wrapperStore';

const count = ref(0)
const store = inject<IStore>('store');
</script>

<template>
  <div>
    <h3>Vue MF MFE</h3>
    <div class="card">
      <button type="button" @click="count++">count is {{ count }}</button>
    </div>
    <span>Counter from Host: {{ store?.rootCounter }}</span>
  </div>
</template>

<style scoped>
.read-the-docs {
  color: #888;
}
</style>

// react-remote-mf-app/src/App.tsx
import { useState } from 'react'
import './App.css'

interface AppProps {
  rootCounter?: number
}

function App(props?: AppProps) {
  const [count, setCount] = useState(0)

  return (
    <div>
      <h3>React MF MFE</h3>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
      </div>
        <span>Counter from Host: {props?.rootCounter}</span>
    </div>
  )
}

export default App
